[package]
name = "my_redis"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = {version="1", features = ["full"]}
bytes = { version = "1" }
clap = { version = "3.1.18", features = ["derive"] }